services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: postgress
      POSTGRES_DB: learning-path
    ports:
      - "5432:5432"
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/init.sql
